<a href="https://colab.research.google.com/github/sergey-kravchenko-km/KM_jupyterlabs/blob/main/Lb7_Kravchenko.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа 7

# Построение бинарного дерева поиска. Подсчёт количества элементов в дереве

Кравченко Сергей, 1 курс 5 группа

## Задание 7.1. Определение классов

In [56]:
from google.colab import files

uploaded = files.upload()

Saving numbers1.txt to numbers1 (7).txt


In [57]:
class EmptyNode:
    def __init__(self):
        pass
    # Метод вставления "останавливается", когда достигает пустого элемента
    def insert(self, value):
        return BinaryNode(self, value, self)
    # Отображение пустого элемента
    def __repr__(self):
        return "*"

class BinaryTree:
    def __init__(self, *args):
        self.root = EmptyNode() # Пустое дерево изначально содержит один пустой элемент

        # Если даны данные, записываем их в дерево
        if len(args) > 0:
            for x in args[0]:
                self.root = self.root.insert(x)
    def __repr__(self):
        return repr(self.root)       # Благодаря рекурсивному вызову выведется всё дерево
    def insert(self, value):
        self.root = self.root.insert(value)  # Произойдёт просеивание элемента сверху вниз

class BinaryNode:
    def __init__(self, left, value, right):
        self.left = left
        self.value = value
        self.right = right
    def __repr__(self):
        return f'({self.left}, {self.value}, {self.right})'

## Задание 7.2. Метод вставки элемента в бинарное дерево поиска

In [58]:
class BinaryNode:
    def __init__(self, left, value, right):
        self.left = left
        self.value = value
        self.right = right
    def __repr__(self):
        return f'({self.left}, {self.value}, {self.right})'

    # Метод вставки
    def insert(self, value):
        '''if '__iter__' in dir(value) and not (isinstance(value,str) and len(value)==1):
            for x in value:
                self.insert(x)
            return self
        '''
        alpha = value < self.value
        if alpha:
            self.left = self.left.insert(value)
        else:
            self.right = self.right.insert(value)
        return self

In [59]:
import random

test_array = [random.randint(0,50) for x in range(20)]
print(test_array,'\n')

tree = BinaryTree(test_array)
print(tree,"\n")

test_generator = range(25)
tree2 = BinaryTree(test_generator)
print(tree2,"\n")

test_str = "Hello, World!"
tree3 = BinaryTree(test_str)
print(tree3, "\n")

[44, 27, 17, 25, 8, 44, 4, 36, 12, 33, 14, 21, 40, 42, 2, 40, 22, 33, 30, 49] 

((((((*, 2, *), 4, *), 8, (*, 12, (*, 14, *))), 17, ((*, 21, (*, 22, *)), 25, *)), 27, (((*, 30, *), 33, (*, 33, *)), 36, (*, 40, ((*, 40, *), 42, *)))), 44, (*, 44, (*, 49, *))) 

(*, 0, (*, 1, (*, 2, (*, 3, (*, 4, (*, 5, (*, 6, (*, 7, (*, 8, (*, 9, (*, 10, (*, 11, (*, 12, (*, 13, (*, 14, (*, 15, (*, 16, (*, 17, (*, 18, (*, 19, (*, 20, (*, 21, (*, 22, (*, 23, (*, 24, *))))))))))))))))))))))))) 

(((*,  , (*, !, *)), ,, *), H, ((*, W, (*, d, *)), e, (*, l, (*, l, ((*, l, *), o, (*, o, (*, r, *))))))) 



## Задание 7.3. Построение бинарного дерева поиска

In [60]:
from google.colab import files

uploaded = files.upload()

Saving matrix.txt to matrix (6).txt


In [61]:
from google.colab import files

uploaded = files.upload()

Saving numbers1.json to numbers1 (5).json


In [62]:
# 1 - Столбец из чисел

print("------------ СТОЛБЕЦ -------------\n")

numbers = []

with open("numbers1.txt") as f:
    for l in f.readlines():
        numbers.append(int(l.rstrip()))

print(numbers,end='\n\n')

tree = BinaryTree(numbers)
print(tree)

# 2 - Матрица (числа разделены пробелами)
import numpy as np

numbers = []
print("\n------------ МАТРИЦА -------------\n")

data = np.loadtxt("matrix.txt", dtype=int)
print(data)

tree = BinaryTree(data.flatten())
print(tree)

# 3 - Пробелы
numbers = []
print("\n------------ ПРОБЕЛЫ -------------\n")

with open("spaces.txt") as f:
    for l in f.readlines():
        numbers += [int(x) for x in l.rstrip().split()]

print(numbers,end='\n\n')

tree = BinaryTree(numbers)
print(tree,end="\n")

# 4 - JSON
import json
from collections import deque

print("\n------------- JSON ---------------\n")

def initialize(d):
    # Учитывая порядок вхождений в дерево,
    # логичным будет применить BFS для последовательного
    # "хождения" по дереву и записи в него соответствующих
    # значений. Для реализации данного метода эффективным
    # будет использовать класс deque встроенного модуля collections
    # (двусторонняя очередь)
    a = []
    Q = deque()
    Q.append(d)
    while len(Q):
        item = Q.popleft()
        if len(item.keys()) > 0:
            a.append(item["value"])
            Q.append(item["left"])
            Q.append(item["right"])
        else:
            ...
    return a

with open("data.json") as f:
    # в качестве аргумента функции json.load() указываем
    # файловый объект, указывающий на *.json файл, в котором
    # записано дерево, далее с помощью BFS расшифровываем дерево
    # и записываем в объект типа BinaryTree
    data = json.load(f)

tree = BinaryTree(initialize(data))
print(tree)

------------ СТОЛБЕЦ -------------

[4, 12, 54, 1, 45, 2, 3, 4, 1, 10, 39, 78]

((*, 1, ((*, 1, *), 2, (*, 3, *))), 4, ((*, 4, (*, 10, *)), 12, (((*, 39, *), 45, *), 54, (*, 78, *))))

------------ МАТРИЦА -------------

[[1 2 3 4 5]
 [4 5 2 1 5]
 [0 1 4 2 4]
 [2 7 3 4 2]
 [0 8 9 7 4]]
((*, 0, (*, 0, *)), 1, ((*, 1, (*, 1, *)), 2, ((*, 2, (*, 2, (*, 2, (*, 2, *)))), 3, ((*, 3, *), 4, ((*, 4, (*, 4, (*, 4, (*, 4, (*, 4, *))))), 5, (*, 5, (*, 5, (*, 7, ((*, 7, *), 8, (*, 9, *))))))))))

------------ ПРОБЕЛЫ -------------



FileNotFoundError: [Errno 2] No such file or directory: 'spaces.txt'

## Задание 7.4. Перегрузка операции принадлежности in

In [ ]:
class BinaryTree:
    def __init__(self, *args):
        self.root = EmptyNode()

        if len(args) > 0:
            for x in args[0]:
                self.root = self.root.insert(x)
    def __repr__(self):
        return repr(self.root)
    def insert(self, value):
        self.root = self.root.insert(value)

    def __contains__(self,value):
        return value in self.root

class BinaryNode:
    def __init__(self, left, value, right):
        self.left = left
        self.value = value
        self.right = right
    def __repr__(self):
        return f'({self.left}, {self.value}, {self.right})'
    def insert(self, value):
        if '__iter__' in dir(value) and not (isinstance(value,str) and len(value)==1):
            for x in value:
                self.insert(x)
            return self
        alpha = value < self.value
        if alpha:
            self.left = self.left.insert(value)
        else:
            self.right = self.right.insert(value)
        return self

    def __contains__(self,value):
        if value == self.value:
            return True
        elif value > self.value:
            return value in self.right
        elif value < self.value:
            return value in self.left

class EmptyNode:
    def __init__(self):
        pass
    def insert(self, value):
        return BinaryNode(self, value, self)
    def __repr__(self):
        return "*"

    def __contains__(self,value):
        return False

In [ ]:
source_data = [5,1,10,3,4]
tree = BinaryTree()
for i in source_data:
    tree.insert(i)
    print(tree)
for i in range(10):
    print((i, i in tree), end = ' ')

print("\n")
tree = BinaryTree("Hello, wolrd!")
abc = "abcdefghijklmnopqrstuvwxyz"
print([x for x in abc if x in tree])
# h заглавная в дереве, поэтому в списке её не будет

tree = BinaryTree([True,True,34,90,0])
[(x, x in tree) for x in [True,False]]
# int-эквивалент False - это 0

## Задание 7.5. Перегрузка встроенной функции len

In [ ]:
class BinaryTree:
    def __init__(self, *args):
        self.root = EmptyNode()

        if len(args) > 0:
            for x in args[0]:
                self.root = self.root.insert(x)
    def __repr__(self):
        return repr(self.root)
    def insert(self, value):
        self.root = self.root.insert(value)
    def __contains__(self,value):
        return value in self.root

    def __len__(self):
        return len(self.root)

class BinaryNode:
    def __init__(self, left, value, right):
        self.left = left
        self.value = value
        self.right = right
    def __repr__(self):
        return f'({self.left}, {self.value}, {self.right})'
    def insert(self, value):
        if '__iter__' in dir(value) and not (isinstance(value,str) and len(value)==1):
            for x in value:
                self.insert(x)
            return self
        alpha = value < self.value
        if alpha:
            self.left = self.left.insert(value)
        else:
            self.right = self.right.insert(value)
        return self
    def __contains__(self,value):
        if value == self.value:
            return True
        elif value > self.value:
            return value in self.right
        elif value < self.value:
            return value in self.left

    def __len__(self):
        return len(self.right)+1+len(self.left)

class EmptyNode:
    def __init__(self):
        pass
    def insert(self, value):
        return BinaryNode(self, value, self)
    def __repr__(self):
        return "*"
    def __contains__(self,value):
        return False

    def __len__(self):
        return 0

In [ ]:
tree = BinaryTree()
for i in source_data:
    tree.insert(i)
print(len(tree), tree, end="\n\n")

tree = BinaryTree("Hello, world!")
print(len(tree), tree,end='\n\n')

tree = BinaryTree()
print(len(tree), tree)

## Задание 7.6. Трассировка объектного уровня

### Задание 1. Вставка вершины в непустое дерево.

Создание и инициализация непустого дерева

$\verb+tree = BinaryTree([5,2,6])      # непустое дерево+$

Дерево после инициализации:
![image.png](attachment:acc6fd58-2b16-4712-9a7a-45f801024ec2.png)

Вставка элемента в непустое дерево:

$\verb+tree.insert(3)+$

Что происходит? вызов метода tree.insert(3) - метод insert класса BinaryTree
1) вычисляем $\verb+self.root.insert(3)+$, $\verb+self.root+$ ссылается на объект типа BinaryNode
2) $\verb+value < self.value (3 < 5) - True+$ => к self.left приравниваем результат операции self.left.insert(3)
3) self.left.insert(3): (далее в объекте типа BinaryNode на который ссылается self.left) value < self.value (3 < 2) - False => к self.right приравниваем результат операции self.right.insert(3)
4) self.right.insert(3): (далее в объекте типа EmptyNode, на который ссылается self.right) метод insert класса EmptyNode возвращает экземпляр BinaryNode(self,value,self) - далее в местах "приравнивания" подставляем вычисленные значения.

Дерево после выполнения $\verb+tree.insert(3)+$:

![image.png](attachment:8ccbea05-384d-4d76-91d5-6aaeb04437b7.png)

### Задание 2. Создание пустого дерева

Создание пустого дерева происходит в несколько этапов:
1) Создаётся объект типа $\verb+BinaryTree+$ с последующим вызовом у него метода инициализации $\verb+__init__(self)+$
2) В методе $\verb+__init__(self)+$ создаётся аттрибут-свойство $\verb+self.root+$ которому присваевается новый объект типа $\verb+EmptyNode+$. Тут же происходит инициализация этого объекта. Далее для обозначения пустого элемента мы будем ссылаться только к нему
3) В $\verb+__init__(self)+$ объекта $\verb+EmptyNode+$ не происходит ничего, поэтому у нас получается пустой экземпляр класса $\verb+EmptyNode+$ ("заглушка")

После создания и инициализации пустое дерево схематично выглядит следующим образом:
![image.png](attachment:c46695da-3afb-4e47-93e5-561e8449378b.png)

### Задание 3. Вставка следующего элемента

Вставка следующей новой вершины:
$\verb+tree.insert(source_data[2])+$

Дерево до вставки:
![image.png](attachment:cc59ecea-c90a-4570-b9e9-34c3e52bf951.png)

После вставки был создан новый объект типа $\verb+BinaryNode+$, появились новые ссылки на $\verb+EmptyNode+$:
![image.png](attachment:ddfc87e2-4327-4163-bb73-bc88dd83f900.png)